version: "3"
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ./homarr-data/configs:/app/data/configs
      - ./homarr-data/icons:/app/public/icons
      - ./homarr-data/data:/data
    ports:
      - 7575:7575
networks: {}
